### ISSUE TITLE
Allow specifying a colour during logger extension creation

### ISSUE THREAD

**Issue by pke** [onubo/react-native-logs#34]
I'd like to colour my loggers with a specific colour.

Would be helpful if during `extend` one could specify options for each transport like:

```ts
const logger = mainLogger.extend("api", { consoleTransport: { colour: "darkgray"  } })
```

**Comment by alessandro-bottamedi** [comment]
At the moment it is only possible to colour by level, not by namespace/extension, but this is a function I absolutely must add as soon as possible, you are right...

Like the possibility to choose which colour, I just have to find a way to manage this option since it is the transports that take care of colouring the logs not the library...

**Comment by pke** [comment]
Maybe like I wrote in the example. One can specify the transporter name and supply options only the transporter understands. 
Then console transporter could then colour the level and the message differently if a custom colour was set, otherwise the behaviour stays as it is now

**Comment by alessandro-bottamedi** [comment]
From v 4.0.0 in the consoleTransport it is possible to choose the color of the log levels and also the colors of the extensions.

**Comment by pke** [comment]
Thanks, great work!
I think I will add the option to generate a random colour for my loggers, that don't specify a colour.
